function [ Res ] = MG_Calc_Res(Res,one,two,three,four,five,T_grid,RHS,n,inx)
% function that calculate the residual of the linear problem Ax=b
% recive the separated A( one:five) matrix and RHS
% return the residual matrix in each grid accordingly to user's input n

Res(2:n(inx)-1,2:n(inx)-1,inx)=    RHS(2:n(inx)-1,2:n(inx)-1,inx)        -( +...
    (two(2:n(inx)-1,2:n(inx)-1,inx)).* T_grid(3:n(inx),2:n(inx)-1,inx)     +...
    (three(2:n(inx)-1,2:n(inx)-1,inx)).* T_grid(1:n(inx)-2,2:n(inx)-1,inx)   +...
    (four(2:n(inx)-1,2:n(inx)-1,inx)).* T_grid(2:n(inx)-1,3:n(inx),inx)     +...
    (five(2:n(inx)-1,2:n(inx)-1,inx)).* T_grid(2:n(inx)-1,1:n(inx)-2,inx)   -...
    (one(2:n(inx)-1,2:n(inx)-1,inx)).* T_grid(2:n(inx)-1,2:n(inx)-1,inx))   ;

end

